"""empty message

Revision ID: 0677957aea94
Revises: c80fb7f4cb48
Create Date: 2022-04-02 14:05:12.953333

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0677957aea94'
down_revision = 'c80fb7f4cb48'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_column('price')

    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('owner_name', sa.String(length=225), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('owner_name')

    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price', sa.INTEGER(), nullable=True))

    # ### end Alembic commands ###
