"""empty message

Revision ID: 0a483e7ace5e
Revises: c852f317f6c9
Create Date: 2022-02-16 22:39:55.376595

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a483e7ace5e'
down_revision = 'c852f317f6c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('seller', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type_', sa.String(length=125), nullable=False))
        batch_op.alter_column('phone1',
               existing_type=sa.VARCHAR(length=12),
               nullable=False)
        batch_op.drop_column('type')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('seller', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.VARCHAR(length=125), nullable=False))
        batch_op.alter_column('phone1',
               existing_type=sa.VARCHAR(length=12),
               nullable=True)
        batch_op.drop_column('type_')

    # ### end Alembic commands ###
