"""empty message

Revision ID: 0df3553733ad
Revises: fbbb3b88c1b6
Create Date: 2022-04-16 20:38:30.489682

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0df3553733ad'
down_revision = 'fbbb3b88c1b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('currency_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_product_currency_id_currency'), 'currency', ['currency_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_product_currency_id_currency'), type_='foreignkey')
        batch_op.drop_column('currency_id')

    # ### end Alembic commands ###
