"""empty message

Revision ID: 19bd4edccfee
Revises: 5be413189973
Create Date: 2022-04-20 17:00:00.283035

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19bd4edccfee'
down_revision = '5be413189973'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('super_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=125), nullable=False),
    sa.Column('password', sa.String(length=125), nullable=False),
    sa.Column('role', sa.Integer(), nullable=False),
    sa.Column('card_id', sa.Integer(), nullable=True),
    sa.Column('active_discount', sa.Boolean(), nullable=True),
    sa.Column('group', sa.String(length=225), nullable=True),
    sa.Column('display_currency_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['display_currency_id'], ['currency.id'], name=op.f('fk_super_user_display_currency_id_currency')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_super_user')),
    sa.UniqueConstraint('email', name=op.f('uq_super_user_email'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('super_user')
    # ### end Alembic commands ###
