"""empty message

Revision ID: 1e544f8f9f3b
Revises: 
Create Date: 2022-02-16 22:31:33.069094

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e544f8f9f3b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('seller', sa.Column('buisness_type', sa.String(length=125), nullable=False))
    op.drop_column('seller', 'type')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('seller', sa.Column('type', sa.VARCHAR(length=125), nullable=False))
    op.drop_column('seller', 'buisness_type')
    # ### end Alembic commands ###
