"""empty message

Revision ID: 1f0b1c9e3fca
Revises: e113fed9967b
Create Date: 2022-12-30 14:01:47.994212

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f0b1c9e3fca'
down_revision = 'e113fed9967b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('img', sa.Integer(), nullable=True))
        batch_op.drop_constraint('fk_customer_avatar_customer_avatar', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_customer_img_customer_avatar'), 'customer_avatar', ['img'], ['id'])
        batch_op.drop_column('avatar')

    with op.batch_alter_table('seller', schema=None) as batch_op:
        batch_op.add_column(sa.Column('img', sa.Integer(), nullable=True))
        batch_op.drop_constraint('fk_seller_logo_company_logo', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_seller_img_company_logo'), 'company_logo', ['img'], ['id'])
        batch_op.drop_column('logo')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('seller', schema=None) as batch_op:
        batch_op.add_column(sa.Column('logo', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_seller_img_company_logo'), type_='foreignkey')
        batch_op.create_foreign_key('fk_seller_logo_company_logo', 'company_logo', ['logo'], ['id'])
        batch_op.drop_column('img')

    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('avatar', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_customer_img_customer_avatar'), type_='foreignkey')
        batch_op.create_foreign_key('fk_customer_avatar_customer_avatar', 'customer_avatar', ['avatar'], ['id'])
        batch_op.drop_column('img')

    # ### end Alembic commands ###
