"""empty message

Revision ID: 4685c35ff1d3
Revises: d72a6970fb65
Create Date: 2022-04-09 01:25:47.500740

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4685c35ff1d3'
down_revision = 'd72a6970fb65'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('active_discount', sa.Boolean(), nullable=True))

    with op.batch_alter_table('seller', schema=None) as batch_op:
        batch_op.add_column(sa.Column('active_discount', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('seller', schema=None) as batch_op:
        batch_op.drop_column('active_discount')

    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.drop_column('active_discount')

    # ### end Alembic commands ###
