"""empty message

Revision ID: 4a66b1840bf5
Revises: 
Create Date: 2022-04-05 23:04:17.126349

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a66b1840bf5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coupons',
    sa.Column('promotion_id', sa.Integer(), nullable=False),
    sa.Column('coupon_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['coupon_id'], ['coupon.id'], ),
    sa.ForeignKeyConstraint(['promotion_id'], ['promotion.id'], ),
    sa.PrimaryKeyConstraint('promotion_id', 'coupon_id', name=op.f('pk_coupons'))
    )
    with op.batch_alter_table('coupon', schema=None) as batch_op:
        batch_op.drop_constraint('uq_coupon_code', type_='unique')
        batch_op.drop_column('code')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('coupon', schema=None) as batch_op:
        batch_op.add_column(sa.Column('code', sa.VARCHAR(length=48), nullable=True))
        batch_op.create_unique_constraint('uq_coupon_code', ['code'])

    op.drop_table('coupons')
    # ### end Alembic commands ###
