"""empty message

Revision ID: 7b3fd53550f4
Revises: 4a66b1840bf5
Create Date: 2022-04-05 23:22:50.884584

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b3fd53550f4'
down_revision = '4a66b1840bf5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('coupon', schema=None) as batch_op:
        batch_op.add_column(sa.Column('code', sa.String(length=18), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('coupon', schema=None) as batch_op:
        batch_op.drop_column('code')

    # ### end Alembic commands ###
