"""empty message

Revision ID: 7ca3b5dc96b2
Revises: 
Create Date: 2022-02-19 14:39:54.972057

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ca3b5dc96b2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company_logo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('path', sa.String(length=125), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('customer_avatar',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('path', sa.String(length=125), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('customer',
    sa.Column('email', sa.String(length=125), nullable=False),
    sa.Column('password', sa.String(length=125), nullable=False),
    sa.Column('role', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nickname', sa.String(length=50), nullable=False),
    sa.Column('avatar', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['avatar'], ['customer_avatar.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('seller',
    sa.Column('email', sa.String(length=125), nullable=False),
    sa.Column('password', sa.String(length=125), nullable=False),
    sa.Column('role', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=True),
    sa.Column('last_name', sa.String(length=50), nullable=True),
    sa.Column('company_name', sa.String(length=125), nullable=False),
    sa.Column('country', sa.String(length=125), nullable=False),
    sa.Column('type', sa.String(length=125), nullable=False),
    sa.Column('phone', sa.String(length=12), nullable=False),
    sa.Column('logo', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['logo'], ['company_logo.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('seller')
    op.drop_table('customer')
    op.drop_table('customer_avatar')
    op.drop_table('company_logo')
    # ### end Alembic commands ###
