"""empty message

Revision ID: 9b3732fe1292
Revises: 912be6a77f81
Create Date: 2022-03-26 15:09:51.059869

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b3732fe1292'
down_revision = '912be6a77f81'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders',
    sa.Column('card_id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['card_id'], ['card.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], ),
    sa.PrimaryKeyConstraint('card_id', 'order_id', name=op.f('pk_orders'))
    )
    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_category_name'), ['name'])

    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_customer_email'), ['email'])

    with op.batch_alter_table('seller', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_seller_email'), ['email'])

    with op.batch_alter_table('type', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_type_name'), ['name'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('type', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_type_name'), type_='unique')

    with op.batch_alter_table('seller', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_seller_email'), type_='unique')

    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_customer_email'), type_='unique')

    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_category_name'), type_='unique')

    op.drop_table('orders')
    # ### end Alembic commands ###
