"""empty message

Revision ID: a537c44dd660
Revises: 19bd4edccfee
Create Date: 2022-04-20 17:03:01.155095

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a537c44dd660'
down_revision = '19bd4edccfee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('super_user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('super_user',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('email', sa.VARCHAR(length=125), nullable=False),
    sa.Column('password', sa.VARCHAR(length=125), nullable=False),
    sa.Column('role', sa.INTEGER(), nullable=False),
    sa.Column('card_id', sa.INTEGER(), nullable=True),
    sa.Column('active_discount', sa.BOOLEAN(), nullable=True),
    sa.Column('group', sa.VARCHAR(length=225), nullable=True),
    sa.Column('display_currency_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['display_currency_id'], ['currency.id'], name='fk_super_user_display_currency_id_currency'),
    sa.PrimaryKeyConstraint('id', name='pk_super_user'),
    sa.UniqueConstraint('email', name='uq_super_user_email')
    )
    # ### end Alembic commands ###
