"""empty message

Revision ID: a6c57f71f252
Revises: ac9c62e4e19c
Create Date: 2022-02-16 22:34:36.946915

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6c57f71f252'
down_revision = 'ac9c62e4e19c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer',
    sa.Column('email', sa.String(length=125), nullable=False),
    sa.Column('password', sa.String(length=125), nullable=False),
    sa.Column('role', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nickname', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('seller',
    sa.Column('email', sa.String(length=125), nullable=False),
    sa.Column('password', sa.String(length=125), nullable=False),
    sa.Column('role', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=False),
    sa.Column('last_name', sa.String(length=50), nullable=False),
    sa.Column('company_name', sa.String(length=125), nullable=False),
    sa.Column('country', sa.String(length=125), nullable=False),
    sa.Column('buisness_type', sa.String(length=125), nullable=False),
    sa.Column('phone', sa.String(length=12), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('company_logo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('logo', sa.String(length=125), nullable=False),
    sa.Column('seller', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['seller'], ['seller.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('customer_avatar',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('avatar', sa.String(length=125), nullable=False),
    sa.Column('customer', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['customer'], ['customer.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('customer_avatar')
    op.drop_table('company_logo')
    op.drop_table('seller')
    op.drop_table('customer')
    # ### end Alembic commands ###
