"""empty message

Revision ID: a77fdd35b95d
Revises: 234d6e78107c
Create Date: 2022-02-22 18:13:04.134344

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = 'a77fdd35b95d'
down_revision = '234d6e78107c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('seller',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=125), nullable=False),
    sa.Column('password', sa.String(length=125), nullable=False),
    sa.Column('role', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=True),
    sa.Column('last_name', sa.String(length=50), nullable=True),
    sa.Column('company_name', sa.String(length=125), nullable=False),
    sa.Column('country', sa.String(length=125), nullable=False),
    sa.Column('busines_type', sa.Integer(), nullable=True),
    sa.Column('phone', sqlalchemy_utils.PhoneNumberType(length=20), nullable=False),
    sa.Column('logo', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['busines_type'], ['type.id'], ),
    sa.ForeignKeyConstraint(['logo'], ['company_logo.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('product_categories',
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('seller_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.ForeignKeyConstraint(['seller_id'], ['seller.id'], ),
    sa.PrimaryKeyConstraint('category_id', 'seller_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product_categories')
    op.drop_table('seller')
    # ### end Alembic commands ###
