"""empty message

Revision ID: b39dbc223593
Revises: 79b120705657
Create Date: 2022-02-16 22:35:55.353018

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b39dbc223593'
down_revision = '79b120705657'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('seller', sa.Column('phone1', sa.String(length=12), nullable=True))
    op.drop_column('seller', 'phone')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('seller', sa.Column('phone', sa.VARCHAR(length=12), nullable=False))
    op.drop_column('seller', 'phone1')
    # ### end Alembic commands ###
