"""empty message

Revision ID: b78a39c17532
Revises: c1c55e24402d
Create Date: 2022-02-16 22:37:10.713956

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b78a39c17532'
down_revision = 'c1c55e24402d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('seller', 'phone',
               existing_type=sa.VARCHAR(length=12),
               nullable=True)
    op.drop_column('seller', 'phone1')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('seller', sa.Column('phone1', sa.VARCHAR(length=12), nullable=True))
    op.alter_column('seller', 'phone',
               existing_type=sa.VARCHAR(length=12),
               nullable=False)
    # ### end Alembic commands ###
