"""empty message

Revision ID: c1c55e24402d
Revises: b39dbc223593
Create Date: 2022-02-16 22:36:46.195787

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1c55e24402d'
down_revision = 'b39dbc223593'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('seller', 'phone')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('seller', sa.Column('phone', sa.VARCHAR(length=12), nullable=False))
    # ### end Alembic commands ###
