"""empty message

Revision ID: c852f317f6c9
Revises: f4760985bd89
Create Date: 2022-02-16 22:39:35.881044

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c852f317f6c9'
down_revision = 'f4760985bd89'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('seller', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone1', sa.String(length=12), nullable=True))
        batch_op.drop_column('phone')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('seller', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone', sa.VARCHAR(length=12), nullable=True))
        batch_op.drop_column('phone1')

    # ### end Alembic commands ###
