"""empty message

Revision ID: cc24fceea2eb
Revises: 0a483e7ace5e
Create Date: 2022-02-16 22:40:29.330440

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc24fceea2eb'
down_revision = '0a483e7ace5e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('seller', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.String(length=125), nullable=False))
        batch_op.add_column(sa.Column('phone', sa.String(length=12), nullable=False))
        batch_op.drop_column('type_')
        batch_op.drop_column('phone1')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('seller', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone1', sa.VARCHAR(length=12), nullable=False))
        batch_op.add_column(sa.Column('type_', sa.VARCHAR(length=125), nullable=False))
        batch_op.drop_column('phone')
        batch_op.drop_column('type')

    # ### end Alembic commands ###
