"""empty message

Revision ID: d72a6970fb65
Revises: 5928a7a49e01
Create Date: 2022-04-08 23:06:36.519315

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd72a6970fb65'
down_revision = '5928a7a49e01'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('active_codes_for_custmr',
    sa.Column('coupon_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['coupon_id'], ['coupon.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ),
    sa.PrimaryKeyConstraint('coupon_id', 'customer_id', name=op.f('pk_active_codes_for_custmr'))
    )
    op.create_table('active_codes_for_sel',
    sa.Column('coupon_id', sa.Integer(), nullable=False),
    sa.Column('seller_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['coupon_id'], ['coupon.id'], ),
    sa.ForeignKeyConstraint(['seller_id'], ['seller.id'], ),
    sa.PrimaryKeyConstraint('coupon_id', 'seller_id', name=op.f('pk_active_codes_for_sel'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('active_codes_for_sel')
    op.drop_table('active_codes_for_custmr')
    # ### end Alembic commands ###
