"""empty message

Revision ID: f4760985bd89
Revises: b78a39c17532
Create Date: 2022-02-16 22:39:25.360064

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4760985bd89'
down_revision = 'b78a39c17532'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('seller', schema=None) as batch_op:
        batch_op.alter_column('phone',
               existing_type=sa.VARCHAR(length=12),
               nullable=True)
        batch_op.drop_column('phone1')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('seller', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone1', sa.VARCHAR(length=12), nullable=True))
        batch_op.alter_column('phone',
               existing_type=sa.VARCHAR(length=12),
               nullable=False)

    # ### end Alembic commands ###
