"""empty message

Revision ID: fbbb3b88c1b6
Revises: 172f0ae5a54b
Create Date: 2022-04-16 20:25:08.181893

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fbbb3b88c1b6'
down_revision = '172f0ae5a54b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('display_currency_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('fk_customer_display_currency_currency', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_customer_display_currency_id_currency'), 'currency', ['display_currency_id'], ['id'])
        batch_op.drop_column('display_currency')

    with op.batch_alter_table('seller', schema=None) as batch_op:
        batch_op.add_column(sa.Column('display_currency_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('fk_seller_display_currency_currency', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_seller_display_currency_id_currency'), 'currency', ['display_currency_id'], ['id'])
        batch_op.drop_column('display_currency')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('seller', schema=None) as batch_op:
        batch_op.add_column(sa.Column('display_currency', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_seller_display_currency_id_currency'), type_='foreignkey')
        batch_op.create_foreign_key('fk_seller_display_currency_currency', 'currency', ['display_currency'], ['id'])
        batch_op.drop_column('display_currency_id')

    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('display_currency', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_customer_display_currency_id_currency'), type_='foreignkey')
        batch_op.create_foreign_key('fk_customer_display_currency_currency', 'currency', ['display_currency'], ['id'])
        batch_op.drop_column('display_currency_id')

    # ### end Alembic commands ###
